name: Publish to GitHub Packages

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: GITHUB_TOKEN
      - name: Publish to GitHub Packages
        run: mvn --batch-mode deploy -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
      - name: Falha por Conflito de Versões
        if: failure()
        run: |
          echo "::error::Se a falha for devido a versões dessincronizadas entre os módulos (ex: o projeto pai está na 1.1.0 e os filhos na 1.0.0), atualize todos de uma vez rodando localmente:"
          echo "::error::mvn versions:set -DnewVersion=<NOVA_VERSAO> -DgenerateBackupPoms=false"
